# Generated by Django 5.0.3 on 2024-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('publishing_datetime', models.DateTimeField()),
                ('thumbnails_URLs', models.URLField()),
            ],
        ),
    ]
